name: renogy_client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.0
  collection: ^1.17.1
  cron: ^0.5.1
  csv: ^5.0.1
  intl: ^0.18.0
  libserialport: ^0.3.0+1
  logging: ^1.1.1
  path: ^1.8.3
