name: Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dart-lang/setup-dart@v1

    - run: dart pub get
    - run: dart analyze
    - run: dart test
